namespace SpaceExplorationGame.Rendering.Base;

/// <summary>
/// Minimal 5x8 bitmap font for basic text rendering without SDL_TTF dependency.
/// Supports uppercase letters, digits, and basic punctuation.
/// </summary>
public static class MiniBitmapFont
{
    // Each character is 5 pixels wide, 8 pixels tall
    // Stored as bool[40] (8 rows * 5 cols)
    private static readonly Dictionary<char, bool[]> Glyphs = new();

    static MiniBitmapFont()
    {
        // Define characters as strings for readability (# = pixel, . = empty)
        DefineChar('A', """
                        .###.
                        #...#
                        #####
                        #...#
                        #...#
                        #...#
                        .....
                        .....
                        """);
        DefineChar('B', """
                        ####.
                        #...#
                        ####.
                        #...#
                        #...#
                        ####.
                        .....
                        .....
                        """);
        DefineChar('C', """
                        .####
                        #....
                        #....
                        #....
                        #....
                        .####
                        .....
                        .....
                        """);
        DefineChar('D', """
                        ####.
                        #...#
                        #...#
                        #...#
                        #...#
                        ####.
                        .....
                        .....
                        """);
        DefineChar('E', """
                        #####
                        #....
                        ###..
                        #....
                        #....
                        #####
                        .....
                        .....
                        """);
        DefineChar('F', """
                        #####
                        #....
                        ###..
                        #....
                        #....
                        #....
                        .....
                        .....
                        """);
        DefineChar('G', """
                        .####
                        #....
                        #.###
                        #...#
                        #...#
                        .####
                        .....
                        .....
                        """);
        DefineChar('H', """
                        #...#
                        #...#
                        #####
                        #...#
                        #...#
                        #...#
                        .....
                        .....
                        """);
        DefineChar('I', """
                        .###.
                        ..#..
                        ..#..
                        ..#..
                        ..#..
                        .###.
                        .....
                        .....
                        """);
        DefineChar('J', """
                        ..###
                        ...#.
                        ...#.
                        ...#.
                        #..#.
                        .##..
                        .....
                        .....
                        """);
        DefineChar('K', """
                        #...#
                        #..#.
                        ###..
                        #..#.
                        #...#
                        #...#
                        .....
                        .....
                        """);
        DefineChar('L', """
                        #....
                        #....
                        #....
                        #....
                        #....
                        #####
                        .....
                        .....
                        """);
        DefineChar('M', """
                        #...#
                        ##.##
                        #.#.#
                        #...#
                        #...#
                        #...#
                        .....
                        .....
                        """);
        DefineChar('N', """
                        #...#
                        ##..#
                        #.#.#
                        #..##
                        #...#
                        #...#
                        .....
                        .....
                        """);
        DefineChar('O', """
                        .###.
                        #...#
                        #...#
                        #...#
                        #...#
                        .###.
                        .....
                        .....
                        """);
        DefineChar('P', """
                        ####.
                        #...#
                        ####.
                        #....
                        #....
                        #....
                        .....
                        .....
                        """);
        DefineChar('Q', """
                        .###.
                        #...#
                        #...#
                        #.#.#
                        #..#.
                        .##.#
                        .....
                        .....
                        """);
        DefineChar('R', """
                        ####.
                        #...#
                        ####.
                        #..#.
                        #...#
                        #...#
                        .....
                        .....
                        """);
        DefineChar('S', """
                        .####
                        #....
                        .###.
                        ....#
                        ....#
                        ####.
                        .....
                        .....
                        """);
        DefineChar('T', """
                        #####
                        ..#..
                        ..#..
                        ..#..
                        ..#..
                        ..#..
                        .....
                        .....
                        """);
        DefineChar('U', """
                        #...#
                        #...#
                        #...#
                        #...#
                        #...#
                        .###.
                        .....
                        .....
                        """);
        DefineChar('V', """
                        #...#
                        #...#
                        #...#
                        .#.#.
                        .#.#.
                        ..#..
                        .....
                        .....
                        """);
        DefineChar('W', """
                        #...#
                        #...#
                        #.#.#
                        #.#.#
                        ##.##
                        #...#
                        .....
                        .....
                        """);
        DefineChar('X', """
                        #...#
                        .#.#.
                        ..#..
                        ..#..
                        .#.#.
                        #...#
                        .....
                        .....
                        """);
        DefineChar('Y', """
                        #...#
                        .#.#.
                        ..#..
                        ..#..
                        ..#..
                        ..#..
                        .....
                        .....
                        """);
        DefineChar('Z', """
                        #####
                        ...#.
                        ..#..
                        .#...
                        #....
                        #####
                        .....
                        .....
                        """);

        // Digits
        DefineChar('0', """
                        .###.
                        #..##
                        #.#.#
                        ##..#
                        #...#
                        .###.
                        .....
                        .....
                        """);
        DefineChar('1', """
                        ..#..
                        .##..
                        ..#..
                        ..#..
                        ..#..
                        .###.
                        .....
                        .....
                        """);
        DefineChar('2', """
                        .###.
                        #...#
                        ...#.
                        ..#..
                        .#...
                        #####
                        .....
                        .....
                        """);
        DefineChar('3', """
                        .###.
                        #...#
                        ..##.
                        ....#
                        #...#
                        .###.
                        .....
                        .....
                        """);
        DefineChar('4', """
                        ...#.
                        ..##.
                        .#.#.
                        #..#.
                        #####
                        ...#.
                        .....
                        .....
                        """);
        DefineChar('5', """
                        #####
                        #....
                        ####.
                        ....#
                        #...#
                        .###.
                        .....
                        .....
                        """);
        DefineChar('6', """
                        .###.
                        #....
                        ####.
                        #...#
                        #...#
                        .###.
                        .....
                        .....
                        """);
        DefineChar('7', """
                        #####
                        ....#
                        ...#.
                        ..#..
                        ..#..
                        ..#..
                        .....
                        .....
                        """);
        DefineChar('8', """
                        .###.
                        #...#
                        .###.
                        #...#
                        #...#
                        .###.
                        .....
                        .....
                        """);
        DefineChar('9', """
                        .###.
                        #...#
                        .####
                        ....#
                        ...#.
                        .##..
                        .....
                        .....
                        """);

        // Punctuation
        DefineChar('.', """
                        .....
                        .....
                        .....
                        .....
                        .....
                        ..#..
                        .....
                        .....
                        """);
        DefineChar(',', """
                        .....
                        .....
                        .....
                        .....
                        ..#..
                        ..#..
                        .#...
                        .....
                        """);
        DefineChar(':', """
                        .....
                        ..#..
                        .....
                        .....
                        ..#..
                        .....
                        .....
                        .....
                        """);
        DefineChar('-', """
                        .....
                        .....
                        .....
                        .###.
                        .....
                        .....
                        .....
                        .....
                        """);
        DefineChar('+', """
                        .....
                        ..#..
                        .###.
                        ..#..
                        .....
                        .....
                        .....
                        .....
                        """);
        DefineChar('/', """
                        ....#
                        ...#.
                        ..#..
                        .#...
                        #....
                        .....
                        .....
                        .....
                        """);
        DefineChar('(', """
                        ..#..
                        .#...
                        .#...
                        .#...
                        .#...
                        ..#..
                        .....
                        .....
                        """);
        DefineChar(')', """
                        ..#..
                        ...#.
                        ...#.
                        ...#.
                        ...#.
                        ..#..
                        .....
                        .....
                        """);
        DefineChar('[', """
                        .##..
                        .#...
                        .#...
                        .#...
                        .#...
                        .##..
                        .....
                        .....
                        """);
        DefineChar(']', """
                        ..##.
                        ...#.
                        ...#.
                        ...#.
                        ...#.
                        ..##.
                        .....
                        .....
                        """);
        DefineChar('*', """
                        .....
                        .#.#.
                        ..#..
                        .#.#.
                        .....
                        .....
                        .....
                        .....
                        """);
        DefineChar('>', """
                        .....
                        #....
                        .##..
                        ...#.
                        .##..
                        #....
                        .....
                        .....
                        """);
        DefineChar('<', """
                        .....
                        ...#.
                        .##..
                        #....
                        .##..
                        ...#.
                        .....
                        .....
                        """);
        DefineChar('!', """
                        ..#..
                        ..#..
                        ..#..
                        ..#..
                        .....
                        ..#..
                        .....
                        .....
                        """);
        DefineChar('?', """
                        .###.
                        #...#
                        ...#.
                        ..#..
                        .....
                        ..#..
                        .....
                        .....
                        """);
        DefineChar('%', """
                        ##..#
                        ##.#.
                        ..#..
                        .#...
                        .#.##
                        #..##
                        .....
                        .....
                        """);
        DefineChar('#', """
                        .#.#.
                        #####
                        .#.#.
                        .#.#.
                        #####
                        .#.#.
                        .....
                        .....
                        """);
        DefineChar('@', """
                        .###.
                        #...#
                        #.###
                        #.#.#
                        #.##.
                        .####
                        .....
                        .....
                        """);
        DefineChar('=', """
                        .....
                        .....
                        #####
                        .....
                        #####
                        .....
                        .....
                        .....
                        """);
        DefineChar('_', """
                        .....
                        .....
                        .....
                        .....
                        .....
                        #####
                        .....
                        .....
                        """);
        DefineChar('\'', """
                        ..#..
                        ..#..
                        .....
                        .....
                        .....
                        .....
                        .....
                        .....
                        """);
        DefineChar('"', """
                        .#.#.
                        .#.#.
                        .....
                        .....
                        .....
                        .....
                        .....
                        .....
                        """);
        DefineChar('~', """
                        .....
                        .....
                        .#...
                        #.#.#
                        ...#.
                        .....
                        .....
                        .....
                        """);
        DefineChar('^', """
                        ..#..
                        .#.#.
                        .....
                        .....
                        .....
                        .....
                        .....
                        .....
                        """);
        DefineChar('&', """
                        .##..
                        #..#.
                        .##..
                        #..#.
                        #...#
                        .##.#
                        .....
                        .....
                        """);
        DefineChar(';', """
                        .....
                        ..#..
                        .....
                        .....
                        ..#..
                        ..#..
                        .#...
                        .....
                        """);
        DefineChar('$', """
                        ..#..
                        .####
                        #.#..
                        .###.
                        ..#.#
                        ####.
                        ..#..
                        .....
                        """);
        DefineChar('{', """
                        ...#.
                        ..#..
                        .#...
                        ..#..
                        ..#..
                        ...#.
                        .....
                        .....
                        """);
        DefineChar('}', """
                        .#...
                        ..#..
                        ...#.
                        ..#..
                        ..#..
                        .#...
                        .....
                        .....
                        """);
        DefineChar('|', """
                        ..#..
                        ..#..
                        ..#..
                        ..#..
                        ..#..
                        ..#..
                        .....
                        .....
                        """);
        DefineChar('\\', """
                        #....
                        .#...
                        ..#..
                        ...#.
                        ....#
                        .....
                        .....
                        .....
                        """);

        // Lowercase (mapped to uppercase for simplicity)
        for (char c = 'a'; c <= 'z'; c++)
        {
            char upper = char.ToUpper(c);
            if (Glyphs.ContainsKey(upper))
            {
                Glyphs[c] = Glyphs[upper];
            }
        }
    }

    private static void DefineChar(char c, string pattern)
    {
        var pixels = new bool[40];
        int i = 0;
        foreach (char ch in pattern)
        {
            if (ch == '#')
            {
                pixels[i++] = true;
            }
            else if (ch == '.')
            {
                pixels[i++] = false;
            }
            // skip whitespace and newlines
        }
        Glyphs[c] = pixels;
    }

    /// <summary>Character width in pixels.</summary>
    public const int GlyphWidth = 5;

    /// <summary>Character height in pixels.</summary>
    public const int GlyphHeight = 8;

    /// <summary>Get the pixel data for a character, or null if not defined.</summary>
    public static bool[]? GetChar(char c)
    {
        return Glyphs.GetValueOrDefault(c);
    }

    /// <summary>Returns all defined glyph entries (character → pixel data).</summary>
    public static IReadOnlyDictionary<char, bool[]> GetAllGlyphs() => Glyphs;
}
