<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SpaceExplorationGame</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpaceExplorationGame.Engine\SpaceExplorationGame.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Arch" Version="2.0.0" />
    <PackageReference Include="Arch.AOT.SourceGenerator" Version="1.0.1" />
    <PackageReference Include="Arch.System" Version="1.1.0" />
    <PackageReference Include="Arch.System.SourceGenerator" Version="2.0.0" />
  </ItemGroup>

</Project>
